### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jmatsushita**
- [x] works in node v4 to v7
- [x] keeps working in the recent browsers
- [x] has the latest dependency updated

### CODE REVIEW

**Comment by jmatsushita** [comment]
Urg... Wasn't expecting these errors. Looks like bumping all the dependencies up uncovered some other errors which don't appear on my dev machine. I'll try to build inside containers to replicate and troubleshoot.

**Comment by jmatsushita** [comment]
Can't reproduce with the official node image or the nodesource/precise:6.3.0 image which is closest to the travis env. Will try to bump dependencies back down one by one... :/

**Comment by jmatsushita** [comment]
It was `level-test`...

**Comment by mcollina** [comment]
Seems good to me. I'll merge the one in LG, and then this one as well, is it ok for you?

**Comment by jmatsushita** [comment]
Sounds perfect, let's start with this and then I'll finish #36 which needs a tiny bit more work.

**Pull request merged**
